DevOps: move project containers to github package using git workflow
hasadna/anyway-reports pull request #41
Opened 2020-10-03 12:42 UTC by omertalmi5

According to the last news from the docker hub we moving all containers of all projects to store the project's images on GitHub, using github packages.

This PR change and refactor the git workflow CI that already exists.

```
change: main file - push image to GitHub package.
```

I checked only the building and pushing of the image.
**I don't know how to check that the deploying is correct.**

2020-10-03 18:26 UTC, OriHoch requested changes
looks great, thanks!
regarding deploy there shouldn't be any change, it should work as-is

see minor change, also we can't merge yet as I need to do some change on hasadna-k8s to support pulling images from github packages, I'll try to do it this week and then we can merge

2020-10-03 18:26 UTC, OriHoch commented on .github/workflows/main.yml
> +        DOCKER_REPOSITORY_ANYWAY_REPORTS: ${{ env.SERVER }}/${{ env.DOCKER_REPOSITORY_ANYWAY_REPORTS }}
@omertalmi5 why is this change needed? what's the content of env.SERVER?
I think that the deploy script should not change as it only needs the docker image which is available in env.DOCKER_REPOSITORY_ANYWAY_REPORTS

2020-10-04 08:42 UTC, OriHoch commented
I made the changes on the cluster to support pulling these packages, so once the requested change is done, you can merge

2020-10-04 11:09 UTC, omertalmi5 commented
> I made the changes on the cluster to support pulling these packages, so once the requested change is done, you can merge



> I made the changes on the cluster to support pulling these packages, so once the requested change is done, you can merge

Do I need to add the registry name in the begining of the image name, for the k8s would know fron where to pull?

2020-10-04 12:19 UTC, OriHoch approved these changes
you're right, need to specify the registry server, looks good now, @atalyaalon  ready for merge

2020-10-08 18:29 UTC, merged